sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gondov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true gondov/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-west-2'
  app: 'docker-react-us'
  env: 'Dockerreactus-env'
  bucket_name: 'elasticbeanstalk-us-west-2-771429333947'
  bucket_path: 'docker-react-us'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
