sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t gondov/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true gondov/docker-react npm run test
             
