sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t Agondov/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Agondov/docker-react npm run test
             
